# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongchi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('lm_user_id', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('review', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('lm_user_id', models.IntegerField(blank=True, null=True)),
                ('matched_time', models.DateTimeField()),
                ('request_start', models.DateTimeField()),
                ('request_end', models.DateTimeField()),
                ('request_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('request_lon', models.FloatField(blank=True, default=0.0, null=True)),
                ('request_cafe', models.BigIntegerField(blank=True, default=0, null=True)),
                ('request_interest', models.BigIntegerField(blank=True, default=0, null=True)),
                ('request_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
