# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tongchi_app', '0002_history_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Request',
        ),
    ]
