# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongchi_app', '0003_auto_20171024_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lm_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
